services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - ./codes/public:/var/www/html/
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 8000:8000
    volumes:
      - ./import.sql:/docker-entrypoint-initdb.d/0_init.sql
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: trekking
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
